### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by erdnaxeli** [poljar/weechat-matrix-rs#15]
Hi,

Is there a matrix room to discuss about this project?

Thanks.

**Comment by poljar** [comment]
The readme has a badge with the Matrix room:

[![#weechat-matrix](https://img.shields.io/badge/matrix-%23weechat--matrix:termina.org.uk-blue.svg?style=flat-square)](https://matrix.to/#/!twcBhHVdZlQWuuxBhN:termina.org.uk?via=termina.org.uk&via=matrix.org)

**Comment by erdnaxeli** [comment]
Oups sorry, I missed it, thanks.

Btw this button is hard to use with weechat :D
