### ISSUE TITLE
Build error: use of unstable library feature 'atomic_min_max'

### ISSUE THREAD

**Issue by strk** [poljar/weechat-matrix-rs#17]
Anything you can do on the codebase to avoid this ?
```
error[E0658]: use of unstable library feature 'atomic_min_max': easier and faster min/max than writing manual CAS loop
   --> /home/strk/.cargo/registry/src/github.com-1ecc6299db9ec823/atomic-0.5.0/src/ops.rs:263:51   
    |
263 |         mem::transmute_copy(&(*(dst as *const A)).fetch_min(mem::transmute_copy(&val), order),),
    |                                                   ^^^^^^^^^
    |
    = note: see issue #48655 <https://github.com/rust-lang/rust/issues/48655> for more information

```

**Comment by poljar** [comment]
Sure, but not for now. There's a reason [this](https://raw.githubusercontent.com/poljar/weechat-matrix-rs/master/rust-toolchain) file exists.

**Comment by poljar** [comment]
Actually this is in a dependency of ours and due to an old Rust version being used to build the plugin. So no, nothing to do here, please use the Rust version defined in the rust-toolchain file.
