### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by ancarda** [poljar/weechat-matrix-rs#18]
I've followed the README instructions and the plugin is now loaded into Weechat -- I see "matrix" in the "Plugins loaded" message at startup.

I've tried a few ways to use `/connect` and `/server`, but nothing seems to work -- Weechat tries to connect over IRC, not Matrix. I also tried to manually edit `~/.weechat/matrix-rust.conf` (when Weechat wasn't running) but that didn't seem to do anything -- server isn't listed when I do `/server list`.

How can I use this plugin?

**Comment by poljar** [comment]
Sadly we can't re-use the `/server` command so it's scoped behind a `/matrix` command, the semantics are similar to the IRC plugin in Weechat but some commands needed to be subcommands, see `/help matrix`.

That being said, the plugin isn't ready yet for daily use.
