### ISSUE TITLE
Error: API mismatch for plugin

### ISSUE THREAD

**Issue by fesnavarro** [poljar/weechat-matrix-rs#20]
Hello guys,

```
Error: API mismatch for plugin "/home/whatever/.weechat/plugins/matrix.so" (current API: "20200301-03", plugin API:"20200621-01"), failed to load
```

I've installed weechat using lazy apt install with Ubuntu 20.04. I'm using nightly cargo and the compilation was fine. No errors.

This is my first try with weechat, what probable I've missed here?

**Comment by poljar** [comment]
You are missing `weechat-plugin.h` in you include search path. There are a couple of options how to compile this plugin for your Weechat version, more info can be found [here](https://github.com/poljar/rust-weechat/tree/master/weechat#picking-the-correct-weechat-version).

**Comment by poljar** [comment]
This has been answered over at https://github.com/poljar/rust-weechat/issues/30.
