### ISSUE TITLE
The buffer name should be calculated correctly.

### ISSUE THREAD

**Issue by poljar** [poljar/weechat-matrix-rs#3]
Currently buffer names are room ids. This is extremely user unfriendly, the buffer should use the same name as other clients display.

For this the [Room](https://github.com/matrix-org/matrix-rust-sdk/blob/master/src/base_client.rs#L59) struct in the rust-sdk would need to be enhanced to handle events that change the room name as well as provide a method to calculate room display names.

[Nio](https://github.com/poljar/matrix-nio/blob/master/nio/rooms.py#L74) and the [python script](https://github.com/poljar/weechat-matrix/blob/master/matrix/buffer.py#L1154) can be used as a guideline for this.

**Comment by pvonmoradi** [comment]
@poljar Still on `/buffer list`, room ids are listed. This causes buffer-jump plugins such as `go.py` present the room `id`s instead of `alias`s. Any workarounds?

**Comment by poljar** [comment]
Sadly no, the buffer name needs to be unique in Weechat, the only way to guarantee this is to use the room id. You can use the `short_name` in `go.py`.
