### ISSUE TITLE
Allow building on a stable rust release

### ISSUE THREAD

**Issue by wavexx** [poljar/weechat-matrix-rs#34]
It seems that nightly is necessary due to one instance ``get_mut_unchecked``. Would it be possible to avoid this so that we can build it using rust stable?

I know matrix-rs is not "ready" yet, but considering I cannot get the python version to coexist with other plugins, I'd rather go with *something* rather than nothing :).

I was considering trying weechat-matrix-rs and possibly create a debian package for it. To do that though it needs to build on the current debian's packaged version or rust, which is 1.48-~1.49 at the moment.

**Comment by poljar** [comment]
I see what I can do over the weekend, though beware request retrying is missing, so it'll sit there doing nothing if you loose network access.

**Comment by wavexx** [comment]
I do not expect it to be perfect/complete. This is mostly to facilitate testing and maybe also grow some more community though easier installation.

**Comment by poljar** [comment]
Latest master doesn't require nightly anymore.

Fixed by https://github.com/poljar/weechat-matrix-rs/commit/43e6f20d203cb9493c199ed30711cc1cf39bf498.
