### ISSUE TITLE
Shows http links to file instead of mxc links

### ISSUE THREAD

**Issue by erdnaxeli** [poljar/weechat-matrix-rs#36]
Currently when someone share a file, the displayed link is the mxc one, which is not directly usable. It should be translated to the http link with the homeserver url.

**Comment by poljar** [comment]
There is a FIXME in the code for this over [here](https://github.com/poljar/weechat-matrix-rs/blob/master/src/render.rs#L322). The homeserver URL is already passed to the `render()` method, only the formatting needs to be fixed.

Encrypted versions of files should inject the decryption info (key, hash) into the URL like the Python script does.
