### ISSUE TITLE
Users in the nicklist should use display names.

### ISSUE THREAD

**Issue by poljar** [poljar/weechat-matrix-rs#4]
Currently the users in the nicklist are using the full mxid.

For this the [Room](https://github.com/matrix-org/matrix-rust-sdk/blob/master/src/base_client.rs#L59) struct in the rust-sdk would need to be enhanced to all the member changing events and provide a way to calculate the current display name of a user.

**Comment by vbrandl** [comment]
For future readers: The `Room` struct has been moved: https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk_base/src/models/room.rs#L107

**Comment by poljar** [comment]
This is now the case for the [new-state-store](https://github.com/poljar/weechat-matrix-rs/tree/new-state-store) branch. This will be closed once the branch is merged to master.

**Comment by poljar** [comment]
This has been merged.
