### ISSUE TITLE
libmatrix.so static build?

### ISSUE THREAD

**Issue by misterhsp** [poljar/weechat-matrix-rs#46]
Is it possible to get a static build from libmatrix.so? If yes, how?

Thanks...

**Comment by poljar** [comment]
What do you mean by that?

Almost everything is statically compiled in, Rust doesn't support dynamic linking:

```bash
ldd .weechat/plugins/matrix.so
ldd: warning: you do not have execution permission for `.weechat/plugins/matrix.so'
	linux-vdso.so.1 (0x00007ffe88989000)
	libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f3501338000)
	libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f350105a000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3500e44000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3500e29000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3500e08000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f3500cc4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3500cbb000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3500aef000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f3502560000)
```

**Comment by misterhsp** [comment]
I mean statically linked.

...

**Comment by poljar** [comment]
I know what static linking means, I don't know what you would like to change in the context of dynamic Weechat plugins, so that a plugin would be considered to be statically linked. As I pointed out, almost all the libraries that the plugin uses are statically linked.

You'll need to provide more than a 4 word sentence for me to understand what you had in mind.

**Comment by misterhsp** [comment]
As you can see the result is only dynamically linked.

```
file libmatrix.so 
libmatrix.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=78d10f2d7dcaa267cb22eac53713fa171c42adbd, with debug_info, not stripped

```

**Comment by poljar** [comment]
This his how [Weechat](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#compile_plugin) and other dynamic plugin systems in the C world work, while it's technically possible to produce a `.a` static lib of this project, Weechat can't load such files.

**Comment by misterhsp** [comment]
But you could still explain to me how this works.


Am 10.06.21 um 10:22 schrieb poljar:

**Comment by poljar** [comment]
Explain how what works?

**Comment by misterhsp** [comment]
What I asked, what else.

Am 11.06.21 um 19:06 schrieb poljar:

**Comment by catthehacker** [comment]
Rust Reference book has quite good description about what I think you want to know
https://doc.rust-lang.org/reference/linkage.html
