### ISSUE TITLE
Support for proxy (SOCKS5)

### ISSUE THREAD

**Issue by ghost** [poljar/weechat-matrix-rs#47]
Wondering if it's possible to add a configuration option for a proxy (or even multiple proxies), specifically SOCKS5, but I would assume that adding support for others might not be a problem if they're prefixed correctly in the config

**Comment by poljar** [comment]
We're using [reqwest](https://github.com/seanmonstar/reqwest) for our HTTP library and I don't think it supports multiple proxies, it does support [SOCKS5](https://docs.rs/reqwest/0.11.3/reqwest/struct.Proxy.html) via the `socks` feature. That feature is optional in the [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/Cargo.toml#L26) and would need to be enabled in [weechat-matrix](https://github.com/poljar/weechat-matrix-rs/blob/master/Cargo.toml#L39).

Once this is done SOCKS5 support should just work™.
