### ISSUE TITLE
Plugin API Mismatch

### ISSUE THREAD

**Issue by runverzagt** [poljar/weechat-matrix-rs#49]
Using Weechat (v3.0.1) from the DNF package manager on Fedora, I built and installed the plugin.

Upon opening Weechat, I received the following error message:
![screenshot_14:45:10_2021-06-29](https://user-images.githubusercontent.com/5334140/123871599-b07e1f80-d8e8-11eb-97e5-c0e2abd0c619.png)

Which version of Weechat does the plugin currently work with?

**Comment by poljar** [comment]
It works with any recent version, though you need to compile it for your Weechat version.

The docs in [this](https://github.com/poljar/rust-weechat/tree/master/weechat/examples/go#picking-the-correct-weechat-version) example show how you can pick your version at compilation time.

I should probably copy those docs in this repo.

**Comment by runverzagt** [comment]
Awesome, thank you very much for your assistance!
That fixed my issue, one additional step I should mention for posterity is I had to `export` the environment variable and run `cargo clean` before re-building from scratch.

**Comment by cremesk** [comment]
thx for the answer.
but i cant finde a "weechat-plugin.h" on my system.
