### ISSUE TITLE
fail to load plugin on weechat v3.2-1

### ISSUE THREAD

**Issue by cremesk** [poljar/weechat-matrix-rs#52]
```
API mismatch for plugin "/home/creme/.weechat/plugins/matrix.so" (current API: "20210601-01", plugin API: "20200621-01"), failed to load
If plugin "matrix" is old/obsolete, you can delete this file.
```

is the plugin to old for weechat?

**Comment by poljar** [comment]
You need to compile the plugin for the Weechat version you have installed.

This is a duplicate of https://github.com/poljar/weechat-matrix-rs/issues/49, I pointed out that we have some docs how to do this over here: https://github.com/poljar/rust-weechat/tree/master/weechat/examples/go#picking-the-correct-weechat-version, and this resulted in a PR adding this to our docs: https://github.com/poljar/weechat-matrix-rs/pull/50.

**Comment by cremesk** [comment]
thx for the answer.
but i cant find a "weechat-plugin.h" on my system.

**Comment by poljar** [comment]
You might need to install a package called `weechat-dev` or if that fails you can always download `weechat.h` from the Weechat repo.

**Comment by cremesk** [comment]
nice it works now!
