### ISSUE TITLE
matrix-qrcode-0.2.0/src/lib.rs, error[E0658]: arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by flips** [poljar/weechat-matrix-rs#65]
Hi!
I tried browsing the issues, but didn't find something similar.
I got this error trying to do `cargo build` just now:

```
   Compiling matrix-qrcode v0.2.0
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/matrix-qrcode-0.2.0/src/lib.rs:15:10
   |
15 | #![doc = include_str!("../README.md")]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `matrix-qrcode`

To learn more, run the command again with --verbose.
```

Trying to read those suggested links, it looks like it's using a newer/experimental rust version?
(Should I try that? Seems I'm currently running `rustc 1.53.0 (53cb7b09b 2021-06-17)`)

**Comment by poljar** [comment]
Yes you'll need a newer Rust version, we require [1.54.0](https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html), it's not an experimental version, just a newer stable release.

**Comment by flips** [comment]
Thanks, `rustup update` FTW ... 🙂  That worked nicely. Now I need to figure out why all devices are "Not Trusted" after restarting weechat / how to make weechat remember trust settings/keys. I tried `/matrix import keyfile passphrase` again, but it said there was no new keys ... Yet all my encrypted rooms are full of `<Unable to decrypt message>` ...
(Maybe there's a Matrix room or something for smaller questions? This feels a bit like misusing the issue tracker.)

**Comment by poljar** [comment]
Verifying devices isn't yet supported, I'll need to finish up https://github.com/poljar/weechat-matrix-rs/pull/56 for it to be supported. Though viewing if a device is verified is a prerequisite for verifying.

**Comment by flips** [comment]
Oh, interesting 🙂 Before I quit/restarted weechat, everything was decrypted/visible ... 🤔😅

**Comment by poljar** [comment]
Verification in the usual case is separate from being able to decrypt, new unverified devices will be able to decrypt new messages though they won't have access to the history.

You'll have to enable a setting in Element to not send room keys to unverified devices, not sure if other clients have those settings.

**Comment by AkechiShiro** [comment]
Is this issue still relevant ?

**Comment by poljar** [comment]
It isn't.
