### ISSUE TITLE
Failed to log in: invalid state

### ISSUE THREAD

**Issue by erdnaxeli** [poljar/weechat-matrix-rs#76]
Hi,

I juste pulled the last version of the code and I get this error:
> Ruma error Failed to log in: StateStore(Json(Error("expected value", line: 1, column: 1)))

**Comment by poljar** [comment]
The format of the store changed in an incompatible way. You'll have to remove the state and let it be recreated.

You need to remove the directory:

```bash
$WEECHAT_HOME/matrix-rust/$SERVER_NAME
```

For me that would be `~/.weechat/matrix-rust/localhost` if I'm deleting the state for my test server called `localhost`.

**Comment by erdnaxeli** [comment]
Thanks :pray:
